# Generated by Django 2.2.1 on 2019-06-06 21:49

import cafe.models
import dj.choices.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('type', dj.choices.fields.ChoiceField(choices=cafe.models.MenuType, default=5)),
                ('image', models.ImageField(blank=True, default='image_avail.png', null=True, upload_to='')),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
